---
- name: restart httpd
  service: name=httpd state=restarted
  tags:
  - zabbix-server
  - zabbix-server-conf

- name: restart zabbix-server
  service: name=zabbix-server state=restarted
  tags:
  - zabbix-server
  - zabbix-server-conf
