---
- name: install required php5.6 and new libcurl packages
  yum: name={{ item }} state=latest
  with_items:
  - php56w
  - php56w-gd
  - php56w-mysql
  - php56w-bcmath
  - php56w-mbstring
  - php56w-xml
  - php56w-ldap
  - curl
  - curl-debuginfo
  - libcurl
  - libcurl-devel
  tags:
  - zabbix-server

- name: install zabbix-server-mysql and zabbix-web-mysql packages
  yum: name={{ item }} state=present
  with_items:
  - zabbix-server-mysql
  - zabbix-web-mysql
  - zabbix-get
  - httpd
  tags:
  - zabbix-server

- name: install the required package
  yum: name={{ item }} state=present
  with_items:
  - MySQL-python
  - python-pip
  tags:
  - zabbix-server

- name: create required directories
  file: path={{ item.path }} state=directory owner={{ item.owner }} group={{ item.owner }} mode=0755
  with_items:
  - { path: '/root/deploy', owner: 'root' }
  - { path: '/var/lib/zabbix', owner: 'zabbix' }
  - { path: '/var/log/snmptrap', owner: 'zabbix' }
  - { path: '/etc/zabbix/web/', owner: 'apache' }
  tags:
  - zabbix-server

- name: copy dbinit scripts to /root/deploy
  template: src={{ item }}.j2 dest=/root/deploy/{{ item }} mode=0755 owner=root group=root
  with_items:
  - zabbix_server_db_init.sh
  tags:
  - zabbix-server

- name: run zabbix_server_db_init.sh
  shell: /root/deploy/zabbix_server_db_init.sh
  args:
    creates: /var/lib/.ansible_zabbix_server_dbinitialized
  tags:
  - zabbix-server

- name: configure /etc/zabbix/zabbix_server.conf
  template: src=zabbix_server.conf.j2 dest=/etc/zabbix/zabbix_server.conf owner=zabbix group=zabbix mode=0644
  notify: restart zabbix-server
  tags:
  - zabbix-server
  - zabbix-server-conf

- name: configure /etc/httpd/conf.d/zabbix.conf
  template: src=zabbix_httpd.conf.j2 dest=/etc/httpd/conf.d/zabbix.conf owner=apache group=apache mode=0644
  notify: restart httpd
  tags:
  - zabbix-server

- name: configure /usr/share/zabbix/conf/zabbix.conf.php
  template: src=zabbix.conf.php.j2 dest=/usr/share/zabbix/conf/zabbix.conf.php owner=apache group=apache mode=0644
  notify: restart httpd
  tags:
  - zabbix-server

- name: configure /etc/zabbix/web/zabbix.conf.php
  template: src=zabbix.conf.php.j2 dest=/etc/zabbix/web/zabbix.conf.php owner=apache group=apache mode=0644
  notify: restart httpd
  tags:
  - zabbix-server

- name: copy the externalscripts templates
  template: src=externalscripts/{{ item | basename }} dest=/usr/lib/zabbix/externalscripts/{{ item | basename | regex_replace("\.j2","") }} owner=zabbix group=zabbix mode=0755
  with_fileglob:
  - ../templates/externalscripts/*.j2
  tags:
  - zabbix-server
  - zabbix-server-externalscripts

- name: start zabbix server
  service: name=zabbix-server enabled=yes state=started
  tags:
  - zabbix-server

- name: start zabbix httpd server
  service: name=httpd enabled=yes state=started
  tags:
  - zabbix-server
